Disable pytest-pystack for test depending on pytester fixture
bloomberg/pytest-pystack pull request #11
Opened 2024-04-12 07:36 UTC by Czaki

*Issue number of the reported bug or feature request: #10*

**Describe your changes**

Disable `pytest-pystack` on test that uses `pytester` fixture (that starts test in test). 

**Testing performed**

Run tests that crash on main with this change and it works now. 

**Additional context**

This is only a workaround, maybe a better solution will be to implement some stack mechanism, that will be enabled if `pytester` fixture is used.

2024-04-29 17:48 UTC, pablogsal requested changes

2024-04-29 17:48 UTC, pablogsal commented on tests/test_pytest_pystack.py
> +def test_pytester_compat(pytester, capfd):
@Czaki

2024-04-29 20:21 UTC, Czaki commented on tests/test_pytest_pystack.py
> +def test_pytester_compat(pytester, capfd):
@pablogsal my skill in pytest fails. I do not know how to handle exceptions content. When I add additional print I could catch it with `capfd`. Did you know how to workaround this?

2024-06-18 08:45 UTC, Czaki commented
@pablogsal could you trigger tests?

2024-10-21 20:38 UTC, Czaki commented
@pablogsal bump

2024-11-16 20:03 UTC, pablogsal approved these changes

2024-11-16 20:07 UTC, merged

2024-11-16 20:08 UTC, pablogsal commented
Will make a release later